import {env} from "cloudflare:workers";
type B={action?:string;[key:string]:unknown};
const db=()=>{if(!env.DB)throw Error("Database unavailable");return env.DB};
const s=(v:unknown,max=200)=>typeof v==="string"?v.trim().slice(0,max):"";
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:NaN;
const bad=(error:string,status=400)=>Response.json({error},{status});
const fail=(e:unknown)=>{console.error("Water API",e);return bad(e instanceof Error&&e.message.includes("UNIQUE constraint")?"That record already exists.":"The request failed. Try again.",500)};
const methods=["Cash","GCash","Card","Bank transfer"];
export async function GET(request:Request){try{const d=db(),search=s(new URL(request.url).searchParams.get("search"),80),like=`%${search}%`;
 const [customers,products,orders,payments]=await d.batch([
 d.prepare("SELECT c.*,COALESCE((SELECT SUM(o.containers_issued-o.containers_returned) FROM orders o WHERE o.customer_id=c.id AND o.status!='Cancelled'),0) AS containers_out FROM customers c ORDER BY c.id DESC LIMIT 500"),
 d.prepare("SELECT * FROM products ORDER BY id"),
 d.prepare("SELECT o.*,c.name AS customer_name,c.phone AS customer_phone,p.name AS product_name,p.size AS product_size FROM orders o JOIN customers c ON c.id=o.customer_id JOIN products p ON p.id=o.product_id WHERE o.reference LIKE ? OR c.name LIKE ? OR c.phone LIKE ? ORDER BY o.id DESC LIMIT 500").bind(like,like,like),
 d.prepare("SELECT p.*,o.reference FROM payments p JOIN orders o ON o.id=p.order_id ORDER BY p.id DESC LIMIT 100")]);
 return Response.json({customers:customers.results,products:products.results,orders:orders.results,payments:payments.results})
 }catch(e){return fail(e)}}
export async function POST(request:Request){let b:B;try{b=await request.json() as B}catch{return bad("Invalid JSON.")}
 try{const d=db(),now=new Date().toISOString();
 if(b.action==="seed"){const old=await d.prepare("SELECT COUNT(*) AS count FROM products").first<{count:number}>();if(old?.count)return bad("Products already loaded.",409);await d.batch([["Purified Water Refill","5 gallon",3500,100],["Mineral Water Refill","5 gallon",4500,75],["Alkaline Water Refill","5 gallon",6000,60],["Purified Water Bottle","500 mL × 24",18000,40],["New Water Container","5 gallon container",22000,30]].map(x=>d.prepare("INSERT INTO products(name,size,price_cents,stock,active) VALUES(?,?,?,?,1)").bind(...x)));return Response.json({message:"Sample products loaded."})}
 if(b.action==="customer"){const name=s(b.name,100),phone=s(b.phone,30),address=s(b.address,250);if(!name||phone.length<7||!address)return bad("Enter a name, phone and address.");await d.prepare("INSERT INTO customers(name,phone,address,created_at) VALUES(?,?,?,?)").bind(name,phone,address,now).run();return Response.json({message:"Customer added."},{status:201})}
 if(b.action==="product"){const name=s(b.name,100),size=s(b.size,70),price=n(b.priceCents),stock=n(b.stock);if(!name||!size||!Number.isInteger(price)||price<=0||price>1e7||!Number.isInteger(stock)||stock<0||stock>1e6)return bad("Enter valid product details.");await d.prepare("INSERT INTO products(name,size,price_cents,stock,active) VALUES(?,?,?,?,1)").bind(name,size,price,stock).run();return Response.json({message:"Product added."},{status:201})}
 if(b.action==="stock"){const id=n(b.id),delta=n(b.delta);if(!Number.isInteger(id)||!Number.isInteger(delta)||delta===0||Math.abs(delta)>100000)return bad("Enter a valid stock adjustment.");const r=await d.prepare("UPDATE products SET stock=stock+? WHERE id=? AND stock+?>=0").bind(delta,id,delta).run();return r.meta.changes?Response.json({message:"Stock updated."}):bad("Not enough stock or product unavailable.",409)}
 if(b.action==="productStatus"){const id=n(b.id),active=n(b.active);if(!Number.isInteger(id)||![0,1].includes(active))return bad("Invalid product.");const r=await d.prepare("UPDATE products SET active=? WHERE id=?").bind(active,id).run();return r.meta.changes?Response.json({message:"Product updated."}):bad("Product not found.",404)}
 if(b.action==="order"){const customerId=n(b.customerId),productId=n(b.productId),quantity=n(b.quantity),paid=n(b.paidCents),type=s(b.type,20),method=s(b.method,30),issued=n(b.containersIssued),returned=n(b.containersReturned),driver=s(b.driver,80),address=s(b.deliveryAddress,250),notes=s(b.notes,500);
 if(!Number.isInteger(customerId)||!Number.isInteger(productId)||!Number.isInteger(quantity)||quantity<1||quantity>1000||!Number.isInteger(paid)||paid<0||!['Pickup','Delivery'].includes(type)||!methods.includes(method)||!Number.isInteger(issued)||issued<0||issued>quantity||!Number.isInteger(returned)||returned<0||returned>1000||type==='Delivery'&&!address)return bad("Enter valid order, payment and container details.");
 const [c,p]=await d.batch([d.prepare("SELECT id FROM customers WHERE id=?").bind(customerId),d.prepare("SELECT price_cents,stock FROM products WHERE id=? AND active=1").bind(productId)]);const product=p.results[0] as {price_cents:number;stock:number}|undefined;if(!c.results.length||!product)return bad("Choose an existing customer and active product.");const total=product.price_cents*quantity;if(paid>total)return bad("Payment exceeds total.");
 const ref="AF-"+crypto.randomUUID().slice(0,8).toUpperCase();
 const r=await d.prepare("INSERT INTO orders(reference,customer_id,product_id,quantity,type,status,delivery_address,driver,containers_issued,containers_returned,total_cents,paid_cents,notes,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT stock FROM products WHERE id=?)>=?").bind(ref,customerId,productId,quantity,type,"Queued",address,driver,issued,returned,total,paid,notes,now,productId,quantity).run();
 if(!r.meta.changes)return bad("Not enough product stock.",409);
 const decrease=await d.prepare("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?").bind(quantity,productId,quantity).run();if(!decrease.meta.changes){await d.prepare("DELETE FROM orders WHERE id=?").bind(r.meta.last_row_id).run();return bad("Product just sold out. Please refresh.",409)}
 if(paid)await d.prepare("INSERT INTO payments(order_id,amount_cents,method,created_at) VALUES(?,?,?,?)").bind(r.meta.last_row_id,paid,method,now).run();return Response.json({message:`Order ${ref} created.`,reference:ref},{status:201})}
 if(b.action==="status"){const id=n(b.id),status=s(b.status,30);if(!Number.isInteger(id)||!['Processing','Ready','Out for delivery','Completed','Cancelled'].includes(status))return bad("Invalid status.");const old=await d.prepare("SELECT status,type,product_id,quantity FROM orders WHERE id=?").bind(id).first<{status:string;type:string;product_id:number;quantity:number}>();if(!old)return bad("Order not found.",404);const steps=old.type==='Delivery'?['Queued','Processing','Ready','Out for delivery','Completed']:['Queued','Processing','Ready','Completed'];if(status!=='Cancelled'&&steps[steps.indexOf(old.status)+1]!==status||status==='Cancelled'&&!steps.slice(0,-1).includes(old.status))return bad("Invalid status transition.",409);const r=await d.prepare("UPDATE orders SET status=?,fulfilled_at=? WHERE id=? AND status=?").bind(status,status==='Completed'?now:null,id,old.status).run();if(!r.meta.changes)return bad("Order changed; refresh.",409);if(status==='Cancelled')await d.prepare("UPDATE products SET stock=stock+? WHERE id=?").bind(old.quantity,old.product_id).run();return Response.json({message:`Order moved to ${status}.`})}
 if(b.action==="payment"){const id=n(b.id),amount=n(b.amountCents),method=s(b.method,30);if(!Number.isInteger(id)||!Number.isInteger(amount)||amount<1||!methods.includes(method))return bad("Enter a valid payment.");const r=await d.prepare("UPDATE orders SET paid_cents=paid_cents+? WHERE id=? AND status!='Cancelled' AND paid_cents+?<=total_cents").bind(amount,id,amount).run();if(!r.meta.changes)return bad("Payment exceeds balance or order is unavailable.",409);await d.prepare("INSERT INTO payments(order_id,amount_cents,method,created_at) VALUES(?,?,?,?)").bind(id,amount,method,now).run();return Response.json({message:"Payment recorded."})}
 if(b.action==="returnContainers"){const id=n(b.id),count=n(b.count);if(!Number.isInteger(id)||!Number.isInteger(count)||count<=0||count>1000)return bad("Enter a valid return count.");const r=await d.prepare("UPDATE orders SET containers_returned=containers_returned+? WHERE id=? AND status!='Cancelled' AND containers_returned+?<=containers_issued").bind(count,id,count).run();return r.meta.changes?Response.json({message:"Containers returned."}):bad("Return exceeds outstanding containers.",409)}
 return bad("Unknown action.")
 }catch(e){return fail(e)}}
